version: '3.7'

services:
  lib:
    image: node:10
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app:delegated
      - ~/.bash_history:/root/.bash_history
    logging:
      options:
        max-size: 50k
        max-file: '1'
