name: CI

on: [push, pull_request]

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['12']

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup node v${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Cache yarn
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.OS }}-${{ matrix.node }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-${{ matrix.node }}-yarn-

      - name: Install dependencies
        run: yarn install --no-progress --non-interactive --frozen-lockfile

      - name: Build
        run: yarn run build

      - name: Test
        run: yarn run test

      - name: Publish to npmjs
        if: "matrix.node == '12' && startsWith(github.ref, 'refs/tags/')"
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_REGISTRY_AUTH_TOKEN}" > .npmrc
          npm version --no-git-tag-version ${GITHUB_REF/refs\/tags\//}
          npm publish
        env:
          CI: true
          NPM_REGISTRY_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_AUTH_TOKEN }}
